#include <dcmpi.h>

#include "f-headers.h"

using namespace std;

dcmpi_provide37(ocvm_sha1summer,ocvm_reader,ocvm_thresh,ocvm_tessellator,ocvm_local_ps,ocvm_fetcher,ocvm_fetchmerger,ocvm_remover,ocvm_validator,ocvm_mediator,ocvm_mediator_reader,ocvm_mediator_readall_samehost,ocvm_mediator_readall_samehost_client,ocvm_mediator_rangefetcher,ocvm_cxx_aligner,ocvm_cxx_aligner_buddy,ocvm_img_reader,ocvm_maximum_spanning_tree2,ocvm_stitch_writer,ocvm_img_partitioner,ocvm_dim_writer,ocvm_zprojector,ocvm_zprojector_feeder,ocvm_combine_paster,ocvm_dim_writer2,ocvm_cxx_normalizer,ocvm_aggregator,ocvm_single_file_writer,ocvm_warper,ocvm_warp_writer,ocvm_ppm_partitioner,ocvm_warp_mapper,ocvm_scaler,ocvm_mediator_writer,ocvm_ppm_tiler,ocvm_cxx_autoaligner,ocvm_cxx_aligner_autobuddy);
